apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: take-3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: take-3 
  name: take-3
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: take-3
    weight: 100 
